{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "79ce1624",
   "metadata": {},
   "source": [
    "### Q1. Describe three applications for exception processing."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0b8a0f7b",
   "metadata": {},
   "source": [
    "Exceptions are raised when the program is syntactically correct, but the code resulted in an error. This error does not stop the execution of the program, however, it changes the normal flow of the program.\n",
    "Exception handling can be used in various appliations.\n",
    "- For handling files\n",
    "- For handling arithmetic operations\n",
    "- For handling Database operations"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b886fe01",
   "metadata": {},
   "source": [
    "### Q2. What happens if you don't do something extra to treat an exception?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "04abb0cb",
   "metadata": {},
   "source": [
    "If the script explicitly doesn't handle the exception, the program will be forced to terminate abruptly and the code past the line that caused the exception will not get executed."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e7bcf0d7",
   "metadata": {},
   "source": [
    "### Q3. What are your options for recovering from an exception in your script?"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "db2b81b8",
   "metadata": {},
   "source": [
    "We can use __try__ and __except__ statements for recovering from an exception in your script."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1974ca22",
   "metadata": {},
   "source": [
    "### Q4. Describe two methods for triggering exceptions in your script."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bb14e9e1",
   "metadata": {},
   "source": [
    "We can use below 2 methods for triggering exceptions in our script.<br>\n",
    "__Raise__ - Triggers an exception manually using custom exceptions<br>\n",
    "__assert__ - The assert statement is used to continue the execute if the given condition evaluates to True. If the assert condition evaluates to False, then it raises the AssertionError exception with the specified error message."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "87dfd69d",
   "metadata": {},
   "source": [
    "### Q5. Identify two methods for specifying actions to be executed at termination time, regardless of whether or not an exception exists."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "54e3a052",
   "metadata": {},
   "source": [
    "Python has __else__ and __finally__ blocks for specifying actions to be executed at termination time, regardless of whether an exceptions exists or not."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cc44c864",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
